### ISSUE TITLE
[feature] form-based login/logout

### ISSUE THREAD

**Issue by jamiew0w** [kekskurse/go-mail-admin#17]
Hello, love the tool - fantastic work!

I have just one request, due to the sensitive information this tool can expose, would it be possible to implement a form-based login/logout system? I think it would help quite a bit for general security.

Thanks so much!

**Comment by fnetX** [comment]
Hey there, please also have a look at #6 and see if this already addresses your issue. 
In the end I don't think that a form-based system will necessarily improve security as it can also be done wrong and the HTTP Basic Auth should be secure enough.

**Comment by jamiew0w** [comment]
Hi @fnetX, thanks for the quick reply. My primary concern is that basic-auth has no logout functionality at all, short of dumping cache/cookies. (I probably should have added this to the OP, my bad).

Secondary to this though is security surrounding brute-forcing of the basic-auth itself. It's very prone to [brute-forcing](http://tylerrockwell.github.io/defeating-basic-auth-with-hydra/) and even nginx/apaches versions of basic-auth offer no protection witohut having fail2ban setup alongside it (with your own customised config). 

I guess the point I'm getting at is basic-auth *can be okay* but if it can be improved is there any reason why not?

Sorry - I probably worded this really poorly. I think I just have a bias against basic-auth lol. Either way, I'll still be using it anyway :+1:

**Comment by fnetX** [comment]
No, you're perfectly right, the basic-auth is not a wonderful approach. I wouldn't consider it insecure, but it's definitely not the best. As to the logout: I think you can use a private window with most browsers as a workaround. 
In addition, the used library is unmaintained and prone to timing attacks, see https://github.com/99designs/basicauth-go/issues/2

That's why @kekskurse planned on implementing another login system, see the issue I referenced above. 

_It's not in the scope of this project, but an ideal way to have a secure and convenient system administration is probably a secure connection (e.g. via VPN, may be feasible with HTTP Auth, SSL Certs etc as well) to the otherwise inaccessible tools which allows the user to login once so the admin doesn't have to rely on multiple credentials. I'll consider changing my setup to this._

**Comment by kekskurse** [comment]
Hey, i already "started" with anouther auth system. The next step will be to implement some kind of session store. In my first (and fast) research i don`t find a perfect solution but one of them will work. I'm currently really busy with my job, I hope 'I can implement it next week but I'm not sure.  

Im currently not sure how to create something like an seperate API-Key. If my current way will work there will be a config for something like a "form-auth", "basic auth" or "none auth".

**Comment by fnetX** [comment]
If you already started you could push your effort in a separate branch, so we could check it out and help with it. 
If you don't think you can afford the time I could also assign myself and see what I can do.

**Comment by jamiew0w** [comment]
@fnetX awesome job, thanks so much. Gonna close this out - take care!
