### ISSUE TITLE
Allow configuration of IP, eg. localhost

### ISSUE THREAD

**Issue by poetaster** [kekskurse/go-mail-admin#20]
Hi!

Nice work! However, I need to run this behind a proxy which already does ssl and auth and I can't see a way to get go-mail-admin to listen to localhost?

Am I missing something?

**Comment by fnetX** [comment]
If you really need to listen to something else it should be easy to implement. 

A common way to do what you need was solved in #3 by allowing to change the port. You can let go-mail-admin listen to :3000 and have your http(s) proxy listen on :80 and :443 and forward to localhost:3000 via plain http.

**Comment by poetaster** [comment]
Umm, but the app grabs the public domain/ip and can then be called directly on domain.tld:3000 .... and that breaks my proxy security around it.

**Comment by poetaster** [comment]
basically, the line:
http.ListenAndServe(":" + port, router)
should permit specify the server address, not all of them.

**Comment by fnetX** [comment]
Sorry for the commit spam, I had a typo in the Readme and committed exactly the same thing twice :facepalm: 
This is a quick fix which addresses your issue. You can either build it yourself (have a look at the docs/Readme-dev.md) or wait for the maintainer to merge and publish the tiny change.

**Comment by fnetX** [comment]
> basically, the line:

yes exactly, it was technically no big problem, I did it as soon as I was on the PC again. It's not exactly graceful, but that's another topic. I opened an issue about this app's error handling. 



> Umm, but the app grabs the public domain/ip and can then be called directly on domain.tld:3000 .... and that breaks my proxy security around it.

I agree that changing the IP to bind to is somewhat an important feature (and a tiny change so of course it was right to do this), but I still propose you to check if you can find a more general solution because I stumbled over quite many apps which simply bind to everything. It's not uncommon to have the firewall block all connections from outside except to :80, :443 (and other necessarily reachable ports) so you can either let all apps bind to their default or have twice the security :-)

**Comment by poetaster** [comment]
Of course, you're right that I can add a line for the firewall dropping everything incoming on that port. It's just a pattern I apply everywhere (public proxy + cache -> private services), and it seems like the (tm) right way to do things. 

Thanks for the effort!
